feat: introduce flakybot
googleapis/repo-automation-bots pull request #1306
Opened 2021-01-22 18:02 UTC by JustinBeckwith

2021-01-22 18:06 UTC, JustinBeckwith commented
Failing test is a bug in the CI script.  It sees that the `buildcop` folder was deleted, and treats that like a change that requires testing.  This only comes up when we delete bots, so an admin override here is likely fine.

2021-01-22 19:04 UTC, tbpg requested changes
I don't _think_ there is anything to do for the Pub/Sub queue. I think it only depends on the Cloud Function name, which will be updated.

The list of things to do after this looks good. I left a comment about supporting both sets of labels for some amount of time. That would be another TODO related to the script to move from old labels to new.

2021-01-22 19:53 UTC, JustinBeckwith commented on packages/flakybot/__snapshots__/buildcop.js
> +exports['flakybot app testsFailed opens an issue when testsFailed 1'] = {
yup

2021-01-22 19:53 UTC, JustinBeckwith commented on metrics/dashboards.sql
> -  actor.login LIKE "build-cop-bot%" AND
done

2021-01-22 19:53 UTC, JustinBeckwith commented on packages/flakybot/src/flakybot.ts
> +const QUIET_LABEL = 'flakybot: quiet';
This is going to be a one day thing - I'd prefer to leave it out and fix over the weekend if I have to

2021-01-25 15:00 UTC, tbpg approved these changes
Thank you!

2021-01-25 16:59 UTC, merged