feat(owl-bot): create issues if it finds malformed config
googleapis/repo-automation-bots pull request #1940
Opened 2021-06-04 01:00 UTC by danielbankhead

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/repo-automation-bots/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1760 🦕

2021-06-04 01:35 UTC, tmatsuo requested changes

2021-06-04 01:35 UTC, tmatsuo commented on packages/owl-bot/test/handlers.ts
> +    const a = sandbox.spy(octokitSha123.issues, 'create');
`a` seems like too short a name. Can you make it something like `issuesCreateSpy`?

2021-06-04 01:35 UTC, tmatsuo commented
Also, before deploying, we should make sure owl bot installations have a read/write permission on issues.

2021-06-04 02:20 UTC, danielbankhead commented on packages/owl-bot/src/octokit-util.ts
> +    if (issue.title === title) {
The issues returned here are open (see line 99). Do you think it's worth reopening an issue or creating a new one?

2021-06-04 04:15 UTC, tmatsuo approved these changes
I'd wait for @SurferJeffAtGoogle approve this too.

2021-06-04 04:15 UTC, tmatsuo commented on packages/owl-bot/src/octokit-util.ts
> +    if (issue.title === title) {
Ah nice I didn't noticed the filter, then LGTM.

2021-06-04 15:08 UTC, danielbankhead commented
Thanks @tmatsuo, @SurferJeffAtGoogle and I paired on the implementation portion of this while I wrote the tests. I'll verify `owl-bot` has a read/write permission on issues.

2021-06-08 14:51 UTC, bcoe approved these changes
This looks like a very clean implementation, and has great tests 👍 

We should be a little bit mindful when we role this out, we can manually run the scan config command, and then run a command to check if there are any existing dubious configs.

The thing we should keep an eye on is too many issues being opened 😄

2021-06-08 14:51 UTC, bcoe commented on packages/owl-bot/src/handlers.ts
> +      await createIssueIfTitleDoesntExist(
I love method names like this 😄

2021-06-10 23:13 UTC, merged