fix: pull changed files from base repo, not head repo
googleapis/repo-automation-bots pull request #2292
Opened 2021-07-20 23:22 UTC by sofisl

2021-07-20 23:24 UTC, chingor13 approved these changes

2021-07-20 23:24 UTC, chingor13 reviewed
Ideally, we should have a test case that demonstrates this fix (a pull request from a forked repo where the fork name differs)

2021-07-20 23:25 UTC, chingor13 requested changes

2021-07-20 23:25 UTC, chingor13 commented on packages/auto-approve/src/auto-approve.ts
>          owner,
If this is coming from a fork, this should also probably be the head branch's repo's owner as well.

2021-07-20 23:37 UTC, sofisl commented
I agree. I actually spent a good amount of time looking for an example of a webhook event for a fork, but the documentation is pretty sparse in that way (and I didn't have access to Cloud Functions). I can wait to merge if you prefer to add tests first.

2021-07-21 15:41 UTC, chingor13 commented
The PR coming from a fork seems like a case we should ensure is working with test cases/fixtures.

2021-07-23 00:24 UTC, sofisl commented
@chingor13, thanks for providing the webhook event, I added some more tests.

2021-07-23 15:46 UTC, bcoe approved these changes

2021-07-23 15:46 UTC, bcoe commented
LGTM, let's wait for Jeff's feedback Monday though 👍

2021-07-26 16:31 UTC, chingor13 approved these changes

2021-07-26 17:32 UTC, merged