refactor: upgrade to release-please v13
googleapis/repo-automation-bots pull request #3041
Opened 2021-12-23 08:48 UTC by chingor13

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/repo-automation-bots/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2021-12-29 21:37 UTC, chingor13 commented
@bcoe Can probably still review, but we'll wait until the new year to merge when we'll for sure be around to debug.

2021-12-30 22:35 UTC, bcoe commented
@chingor13 probably won't be able to look until new year, I'm glad we have this queued up.

2022-01-04 19:24 UTC, bcoe requested changes
I'm a little worried about dropping the tests for choosing an appropriate branch by default, and allowing this to be overridden in config, is this behavior still caught anywhere.

2022-01-04 19:24 UTC, bcoe commented on packages/release-please/test/release-please.ts
> -    const payload = require(resolve(fixturesPath, './push_to_main'));
Do we have anythiung that confirms we default to the appropriate branch if not config provided? Is there a test for this in release-please itself?

2022-01-04 19:46 UTC, bcoe approved these changes

2022-01-04 20:08 UTC, merged