chore(python): update required checks to include owlbot and GH actions
googleapis/repo-automation-bots pull request #3104
Opened 2022-01-19 12:04 UTC by parthea

Wait for https://github.com/googleapis/synthtool/pull/1333

2022-01-25 20:06 UTC, busunkim96 approved these changes
LGTM, please make sure we aren't breaking any repos that need to keep Kokoro around for system tests.

2022-01-25 20:55 UTC, tswast requested changes
LGTM, but curious how you're handling system tests in the meantime?

Just mailed https://github.com/googleapis/python-db-dtypes-pandas/pull/61 to test out this status checks list in a repo with no system tests.

2022-01-25 20:55 UTC, tswast commented on packages/sync-repo-settings/src/required-checks.json
> -          "Kokoro",
We probably need to wait until system tests are migrated before removing this, unless there are few enough repos that it'd make sense to have a custom `sync-repo-settings.yaml` in those repos temporarily?

2022-01-25 21:37 UTC, tswast approved these changes
As discussed in chat, we'll use `sync-repo-settings.yaml` in repos with system tests.

2022-02-02 00:23 UTC, chingor13 approved these changes

2022-02-07 23:20 UTC, tmatsuo commented
@parthea Is it ready to merge?

2022-02-07 23:25 UTC, merged