fix(owl-bot): only use lock around running post-processor
googleapis/repo-automation-bots pull request #3316
Opened 2022-03-23 21:08 UTC by chingor13

Currently, owlbot obtains a lock on a owner/repo/sha as soon as an event that could trigger a post-processor event runs. Instead, it should only attempt to run the post-processor under a lock.

This change moves the lock acquisition to a helper that wraps the run post-processor logic. This allows the webhook handlers to do their pre-checks and clean up no matter if it actually ends up running the post-processor or not.

Fixes #3257

2022-03-23 22:31 UTC, chingor13 commented on packages/owl-bot/src/owl-bot.ts
> -      lock.release();
Note: we also had an unawaited promise here

2022-03-24 18:01 UTC, SurferJeffAtGoogle requested changes

2022-03-24 18:37 UTC, bcoe commented on packages/owl-bot/src/owl-bot.ts
> +  // Short-circuit if post-processor already running for this SHA:
```suggestion
  // Short-circuit if post-processor already running for this SHA, preventing two post-processor images
  // from both executing and pushing changes against the same PR.
```

2022-03-24 18:39 UTC, bcoe approved these changes
Looks reasonable to me once @SurferJeffAtGoogle's comments are addressed.

2022-03-24 18:39 UTC, bcoe commented on packages/owl-bot/src/owl-bot.ts
> +async function runPostProcessorWithLock(
Now:

```js
  await removeOwlBotRunLabel(owner, repo, prNumber, octokit);
```

will execute, whereas prior to this change the lock was checked before calling.

2022-03-24 19:40 UTC, chingor13 commented on packages/owl-bot/src/owl-bot.ts
> +async function runPostProcessorWithLock(
Yes, previously the `pull_request.labeled` handler tried to do everything under the lock. This prevents the bot from removing the `owlbot:run` label.

Only the actual running of the post-processor requires running under lock. We make it so both the label event handler and the code push event handler call the post-processor with the lock. Any other decision making on whether or not to run is localized in those handlers.

2022-03-25 16:38 UTC, SurferJeffAtGoogle approved these changes

2022-03-25 16:56 UTC, merged