feat: implement flow control for Github webhook and Pub/Sub
googleapis/repo-automation-bots pull request #4406
Opened 2022-09-15 01:38 UTC by tmatsuo

towards #3719

2022-09-15 16:09 UTC, chingor13 requested changes
Since this is in-memory, this assumes that a single frontend instance is handling the initial requests. The effective batch size is `this.batch` (30) x the number of frontend instances (which we do not necessarily control).

If the "frontend" is GCF, then we will have tons of instances and essentially limitless flow. Even for Cloud Run, we probably expect it to scale up when we have an influx of requests which would cause us to want this flow control.

We will also need to make sure that the pubsub push subscriber is pushing to Cloud Run.

2022-09-15 16:13 UTC, chingor13 commented
I think another option would be to improve the error handling in the cases of rate limit errors. Instead of returning 503s to tasks, we could return a 200 (causing this task to succeed), but re-queue the same request to be processed in the future (perhaps even listening to the suggested quota reset header from GitHub). We might also keep the state of whether we are in backoff and immediately re-queue tasks with a delay without attempting to process them until the time is right.

2022-09-15 16:39 UTC, tmatsuo commented
@chingor13 Yes, you're correct, but I think it's fine because I'll deploy Cloud Run frontend for all the bots, and the frontend could handle concurrent requests. Normally even during the burst events, the active instance count goes up to 2 or 3. If there are 3 instnaces, yes, the flow is 3 times bigger, but it's still better than nothing.

Also, we want to control the flow not only for the Github Rate limit errors, but also for Datastore contentions.

2022-09-15 17:07 UTC, tmatsuo commented on packages/gcf-utils/src/flow-limitter.ts
> +export class FlowLimitter {
fixed

2022-09-15 21:09 UTC, tmatsuo commented
In order to make the flow control global, we need to issue additional RPC which will increase the frontend latency.

I like the current in-memory implementation better even if it's not perfect.

2022-09-16 16:05 UTC, tmatsuo commented
It turned out that you can set some parameters for rate limiting with Cloud Task 😂

2022-09-16 16:05 UTC, closed without merging