chore(owlbot-bootstrapper): add python to the list of monorepos
googleapis/repo-automation-bots pull request #4414
Opened 2022-09-16 17:23 UTC by parthea

2022-09-16 17:23 UTC, sofisl approved these changes

2022-09-19 16:03 UTC, chingor13 requested changes
@parthea The tests are not passing. Perhaps the tests were originally written so that python was explicitly not considered a monorepo?

2022-09-19 17:54 UTC, parthea commented
@sofisl Could we remove the split repo functionality?

2022-09-20 16:19 UTC, chingor13 approved these changes
I think this is ok. Confirmed with the Java team that we will want to generate the new libraries into their monorepo. PHP is the other repo that has extra repos, but those just need to be created and this was a separate path anyways.

Will wait for @sofisl to review as well.

2022-09-20 20:37 UTC, sofisl approved these changes

2022-09-20 20:40 UTC, merged