feat: create env variables for MONO_REPO_PATH, SERVICE_CONFIG_PATH, INTER_CONTAINER_VARS_PATH
googleapis/repo-automation-bots pull request #4561
Opened 2022-10-11 00:43 UTC by sofisl

This feature corresponds to the work in the internal doc,`Design Doc: Providing API-specific information in owlbot-bootstrapper`. We've agreed to store the paths in env variables as opposed to constants. 

There's a small refactor in this PR as well that corresponds to the env variables. I separated out a `writeToWellKnownFile` function so that it corresponds to the environment variable that you want to write to, instead of being hidden in an `openABranch` function. This makes the env variable more obvious as to where it's being used.

2022-10-11 16:39 UTC, chingor13 requested changes
This PR mostly looks fine, but it doesn't match the PR title/description. I don't see handling for env variables (I see CLI arguments being read/required).

2022-10-11 22:24 UTC, sofisl commented
@chingor13, added in the cli work (forgot to add it to the commit), PTAL

2022-10-12 16:10 UTC, chingor13 requested changes

2022-10-12 16:10 UTC, chingor13 commented on packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
> +    - "$_INTER_CONTAINER_VARS_PATH"
These should be env vars, not CLI arguments.

Shouldn't the env var that the language container receive for SERVICE_CONFIG_PATH and INTER_CONTAINER_VARS_PATH be paths including the filename? I would not expect each container to have to know/specify the file name within the directory.

2022-10-12 18:53 UTC, merged