gax 3.5.2
googleapis/repo-automation-bots pull request #4650
Opened 2022-11-02 19:07 UTC by alexander-fenster

- fix(deps): use google-gax v3.5.2
- fix(deps): use google-gax v3.5.2

2022-11-02 20:36 UTC, chingor13 requested changes

2022-11-02 20:36 UTC, chingor13 commented on packages/gcf-utils/package.json
> +    "google-gax": "^3.5.2"
looks like we're missing a trailing comma
```suggestion
    "google-gax": "^3.5.2",
```

2022-11-02 20:36 UTC, chingor13 commented on packages/secret-rotator/package.json
> +    "google-gax": "^3.5.2"
```suggestion
    "google-gax": "^3.5.2",
```

2022-11-02 21:51 UTC, sofisl approved these changes

2022-11-02 21:52 UTC, sofisl approved these changes

2022-11-03 17:04 UTC, sofisl approved these changes

2022-11-03 17:05 UTC, sofisl approved these changes

2022-11-03 17:09 UTC, sofisl approved these changes

2022-11-07 17:53 UTC, tmatsuo commented
Our test and deployment scripts run `npm ci`.

Maybe you can run `npm update google-gax --save` to update the package-lock.json too.

2022-11-07 21:21 UTC, alexander-fenster commented
Updated lockfiles. This was a mass change across all repositories that depend on `google-gax`, it may not be that important for `repo-automation-bots`, but let's still have it here as well if CI passes.

2022-11-08 01:01 UTC, tmatsuo approved these changes

2022-11-21 17:53 UTC, chingor13 approved these changes

2022-11-21 17:55 UTC, merged