fix(auto-approve): allow Python major dependency updates
googleapis/repo-automation-bots pull request #4998
Opened 2023-03-14 18:12 UTC by sofisl

Fixes #4126

cc @parthea

2023-03-27 20:00 UTC, chingor13 requested changes

2023-03-29 23:47 UTC, sofisl commented on packages/auto-approve/src/utils-for-pr-checking.ts
> +export function isVersionBumped(versions: Versions): boolean {
We'd want to confirm that it was increasing. You wouldn't want to autoapprove a rollback, for example.

2023-03-30 17:03 UTC, chingor13 requested changes

2023-03-30 17:03 UTC, chingor13 commented on packages/auto-approve/src/utils-for-pr-checking.ts
> +export function isVersionBumped(versions: Versions): boolean {
For readability, please use `semver.gt` or `semver.lt` instead (https://github.com/npm/node-semver#comparison). The `semver.compare` return value (1, 0, -1) is used for sorting.

2023-04-10 17:51 UTC, merged