fix(owl-bot): OwlBot to report a skip in pull request checks
googleapis/repo-automation-bots pull request #5643
Opened 2024-12-23 22:38 UTC by suztomo

- **fix: OwlBot postprocessor to report a check when skipping a PR**
- **test: updated test**

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/repo-automation-bots/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-12-27 21:19 UTC, suztomo commented
"packages-owl-bot-test (repo-automation-bots) Failing after 1s — Summary" says:

> Your build failed to run: generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket', (b) use the REGIONAL_USER_OWNED_BUCKET build.options.default_logs_bucket_behavior option, or (c) use either CLOUD_LOGGING_ONLY / NONE logging options

2024-12-27 21:33 UTC, suztomo commented
All checks have passed

2025-01-03 00:15 UTC, chingor13 requested changes

2025-01-03 00:15 UTC, chingor13 commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
I don't think we want to mark as success. There should be a `skipped` state I think.

2025-01-03 00:19 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
@chingor13 I see it's either success or failure.

```
export interface CheckArgs {
  privateKey: string;
  appId: number;
  installation: number;
  pr: number;
  repo: string;
  summary: string;
  conclusion: 'success' | 'failure';
  detailsURL: string;
  text: string;
  title: string;
}
```

and https://github.com/suztomo/repo-automation-bots/blob/913afc1121af735f358e20394b82b94903c83dc4/packages/owl-bot/src/core.ts#L296

2025-01-03 00:25 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
https://github.com/suztomo/repo-automation-bots/blob/913afc1121af735f358e20394b82b94903c83dc4/packages/owl-bot/src/core.ts#L296 has "skipped".

Now thinking about whether a required check is ok to be skipped (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

2025-01-03 00:29 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
@chingor13 I think we want "success" in the conclusion. Otherwise we would see "Waiting for status to be reported." We also have precedent in https://github.com/googleapis/repo-automation-bots/blob/cacc73c72cfca7ec1bbadf6319f0b9b58c5edb7f/packages/owl-bot/src/owl-bot.ts#L648-L659 (from Tony's comment in the bug) which returns "success" in conclusion.

2025-01-03 17:42 UTC, chingor13 commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
You can create a conclusion of `skipped` https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run.  The referenced `interface` is our own helper declaration.

Also, we can confirm that `skipped` conclusion does pass required checks (look at this PR for the skipped GCB presubmits)

2025-01-03 17:55 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> -  // If the pull request is from a fork and not from allowlist, skip.
Moving this logic after the declaration of `createCheck`.

2025-01-03 17:56 UTC, suztomo reviewed
@chingor13 PTAL

2025-01-03 17:56 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'skipped',
Now it's skipped.

2025-01-03 18:16 UTC, suztomo commented on packages/owl-bot/src/owl-bot.ts
> +      conclusion: 'success',
Updated

2025-01-06 15:41 UTC, meltsufin approved these changes

2025-01-06 16:44 UTC, chingor13 approved these changes

2025-01-06 17:05 UTC, merged